using BenchmarkDotNet.Running;

//BenchmarkRunner.Run<Benchmarking.Benchmarks.ArgumentIncrement.Benchmarks>();
//BenchmarkRunner.Run<Benchmarking.Benchmarks.AsyncTask.Benchmarks>();
//BenchmarkRunner.Run<Benchmarking.Benchmarks.Boxing.Benchmarks>();
//BenchmarkRunner.Run<Benchmarking.Benchmarks.CastingObjects.Benchmarks>();
//BenchmarkRunner.Run<Benchmarking.Benchmarks.CompareStrings.Benchmarks>();
//BenchmarkRunner.Run<Benchmarking.Benchmarks.ConcatStrings.Benchmarks>();
//BenchmarkRunner.Run<Benchmarking.Benchmarks.Enumeration.Benchmarks>();
//BenchmarkRunner.Run<Benchmarking.Benchmarks.EnumToString.Benchmarks>();
//BenchmarkRunner.Run<Benchmarking.Benchmarks.EqualsList.Benchmarks>();
//BenchmarkRunner.Run<Benchmarking.Benchmarks.IntParser.Benchmarks>();
//BenchmarkRunner.Run<Benchmarking.Benchmarks.JSON.Benchmarks>();
//BenchmarkRunner.Run<Benchmarking.Benchmarks.LINQ.Benchmarks>();
//BenchmarkRunner.Run<Benchmarking.Benchmarks.ListIteration.Benchmarks>();
//BenchmarkRunner.Run<Benchmarking.Benchmarks.Logging.Benchmarks>();
//BenchmarkRunner.Run<Benchmarking.Benchmarks.ParallelLoop.Benchmarks>();
//BenchmarkRunner.Run<Benchmarking.Benchmarks.Params.Benchmarks>();
//BenchmarkRunner.Run<Benchmarking.Benchmarks.Reflection.Benchmarks>();
//BenchmarkRunner.Run<Benchmarking.Benchmarks.Span.Benchmarks>();
