using BenchmarkDotNet.Running;

//BenchmarkRunner.Run<Benchmarking.ArgumentIncrement.Benchmarks>();
//BenchmarkRunner.Run<Benchmarking.AsyncTask.Benchmarks>();
//BenchmarkRunner.Run<Benchmarking.Boxing.Benchmarks>();
//BenchmarkRunner.Run<Benchmarking.CastingObjects.Benchmarks>();
//BenchmarkRunner.Run<Benchmarking.CompareStrings.Benchmarks>();
//BenchmarkRunner.Run<Benchmarking.ConcatStrings.Benchmarks>();
//BenchmarkRunner.Run<Benchmarking.Enumeration.Benchmarks>();
//BenchmarkRunner.Run<Benchmarking.EnumToString.Benchmarks>();
//BenchmarkRunner.Run<Benchmarking.EqualsList.Benchmarks>();
BenchmarkRunner.Run<Benchmarking.Find.Benchmarks>();
//BenchmarkRunner.Run<Benchmarking.IntParser.Benchmarks>();
//BenchmarkRunner.Run<Benchmarking.JSON.Benchmarks>();
//BenchmarkRunner.Run<Benchmarking.LINQ.Benchmarks>();
//BenchmarkRunner.Run<Benchmarking.ListIteration.Benchmarks>();
//BenchmarkRunner.Run<Benchmarking.Logging.Benchmarks>();
//BenchmarkRunner.Run<Benchmarking.ParallelLoop.Benchmarks>();
//BenchmarkRunner.Run<Benchmarking.Params.Benchmarks>();
//BenchmarkRunner.Run<Benchmarking.Reflection.Benchmarks>();
//BenchmarkRunner.Run<Benchmarking.Span.Benchmarks>();
